required = ["github.com/codegangsta/gin", "github.com/alecthomas/gometalinter"]

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"
